spring:
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:test
  #    username: sa
  #    password:
  #  h2:
  #    console:
  #      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
auth:
  jwt:
    issuer: team.sparta.com
    secret: J13s2z82HSa5gJG32eSfJbRYBB4Wsgas
    accessTokenExpirationHour: 72